// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmlAW80N2jrG2pppPjSPaEjuPnB7ueuZk',
    appId: '1:636260165485:web:e58a849065a6601eae1c64',
    messagingSenderId: '636260165485',
    projectId: 'todo-app-7a4cc',
    authDomain: 'todo-app-7a4cc.firebaseapp.com',
    storageBucket: 'todo-app-7a4cc.firebasestorage.app',
    measurementId: 'G-1B31DEQZD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfTSnyDW4iXyrytlYYv5KpVU1dvXvUDxY',
    appId: '1:636260165485:android:5bb0fd318c71f510ae1c64',
    messagingSenderId: '636260165485',
    projectId: 'todo-app-7a4cc',
    storageBucket: 'todo-app-7a4cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV2K3vQcAGruHDbSOa2m60gtQ65VzEHfQ',
    appId: '1:636260165485:ios:14bde8371430050dae1c64',
    messagingSenderId: '636260165485',
    projectId: 'todo-app-7a4cc',
    storageBucket: 'todo-app-7a4cc.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV2K3vQcAGruHDbSOa2m60gtQ65VzEHfQ',
    appId: '1:636260165485:ios:14bde8371430050dae1c64',
    messagingSenderId: '636260165485',
    projectId: 'todo-app-7a4cc',
    storageBucket: 'todo-app-7a4cc.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmlAW80N2jrG2pppPjSPaEjuPnB7ueuZk',
    appId: '1:636260165485:web:f755eef8dfb046e4ae1c64',
    messagingSenderId: '636260165485',
    projectId: 'todo-app-7a4cc',
    authDomain: 'todo-app-7a4cc.firebaseapp.com',
    storageBucket: 'todo-app-7a4cc.firebasestorage.app',
    measurementId: 'G-JV3Z4XJ5PQ',
  );
}
