// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK86Ktok6ln866jcNLH9uet6m8sWkim5s',
    appId: '1:947380057613:web:880adca17b3fb0f11e4744',
    messagingSenderId: '947380057613',
    projectId: 'todoapp-26849',
    authDomain: 'todoapp-26849.firebaseapp.com',
    storageBucket: 'todoapp-26849.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgS2UNHlyfBrvFNVLl5UbIUk-Bz6ksOcA',
    appId: '1:947380057613:android:f18824c4494dd4371e4744',
    messagingSenderId: '947380057613',
    projectId: 'todoapp-26849',
    storageBucket: 'todoapp-26849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEe_fdKQ5uLWblbeT9JRYaZ4e9ynzFCk8',
    appId: '1:947380057613:ios:ff1f4313e719b84c1e4744',
    messagingSenderId: '947380057613',
    projectId: 'todoapp-26849',
    storageBucket: 'todoapp-26849.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEe_fdKQ5uLWblbeT9JRYaZ4e9ynzFCk8',
    appId: '1:947380057613:ios:ff1f4313e719b84c1e4744',
    messagingSenderId: '947380057613',
    projectId: 'todoapp-26849',
    storageBucket: 'todoapp-26849.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK86Ktok6ln866jcNLH9uet6m8sWkim5s',
    appId: '1:947380057613:web:9350901676ff13311e4744',
    messagingSenderId: '947380057613',
    projectId: 'todoapp-26849',
    authDomain: 'todoapp-26849.firebaseapp.com',
    storageBucket: 'todoapp-26849.firebasestorage.app',
  );
}
